{application,games,
             [{modules,['Elixir.Games','Elixir.Games.GuessingGame',
                        'Elixir.Games.RockPaperScissors',
                        'Elixir.Games.Wordle']},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger]},
              {description,"games"},
              {registered,[]},
              {vsn,"0.1.0"}]}.
